title: Stephen Adetobi
logo: StockPcImage.jpg
description: Data Analyst with 2 years of experience. Proficient in manipulating data in SQL and Excel, creating flexible dashboards in Power Bi, and importing and automating data pipelines through SSMS.
show_downloads: true
